import { Injectable } from "@nestjs/common";
import { cartItems, carts, customerAddresses, customerSessions, customerTokens, customers } from "@brandcanvas/database";
import { and, asc, eq, gt, isNull } from "drizzle-orm";
import { DatabaseService } from "../../../infrastructure/database";
import type { CustomerAddressDto, CustomerAddressInputDto, CustomerProfileDto, UpdateCustomerProfileDto } from "../dto";
import { CustomerRepository, type CustomerAuthRecord } from "./customer.repository";
const profile = (row: typeof customers.$inferSelect): CustomerProfileDto => ({ id: row.id, email: row.email, firstName: row.firstName, lastName: row.lastName, phone: row.phone, emailVerified: Boolean(row.emailVerifiedAt), marketingConsent: row.marketingConsent });
const address = (row: typeof customerAddresses.$inferSelect): CustomerAddressDto => ({ id: row.id, label: row.label ?? undefined, firstName: row.firstName, lastName: row.lastName, phone: row.phone, addressLine1: row.addressLine1, addressLine2: row.addressLine2, city: row.city, region: row.region, postalCode: row.postalCode, countryCode: row.countryCode, isDefaultShipping: row.isDefaultShipping, isDefaultBilling: row.isDefaultBilling });
@Injectable()
export class DrizzleCustomerRepository implements CustomerRepository {
  constructor(private readonly database: DatabaseService) {}
  async findByEmail(storeId: string, email: string): Promise<CustomerAuthRecord | null> { const [row] = await this.database.db.select().from(customers).where(and(eq(customers.storeId, storeId), eq(customers.email, email))).limit(1); return row ? { ...profile(row), passwordHash: row.passwordHash, storeId: row.storeId, status: row.status } : null; }
  async findById(storeId: string, customerId: string) { const [row] = await this.database.db.select().from(customers).where(and(eq(customers.storeId, storeId), eq(customers.id, customerId))).limit(1); return row ? profile(row) : null; }
  async create(input: { storeId: string; email: string; passwordHash: string; firstName: string; lastName: string; phone?: string; marketingConsent: boolean }) { try { const [row] = await this.database.db.insert(customers).values(input).returning(); if (!row) throw new Error("Customer creation failed."); return profile(row); } catch (error) { if (typeof error === "object" && error && "code" in error && (error as { code?: string }).code === "23505") return "duplicate" as const; throw error; } }
  async updateProfile(storeId: string, customerId: string, input: UpdateCustomerProfileDto) { const [row] = await this.database.db.update(customers).set({ firstName: input.firstName.trim(), lastName: input.lastName.trim(), phone: input.phone?.trim() || null, marketingConsent: input.marketingConsent ?? false, updatedAt: new Date() }).where(and(eq(customers.storeId, storeId), eq(customers.id, customerId))).returning(); return row ? profile(row) : null; }
  async createSession(input: { customerId: string; storeId: string; tokenHash: string; expiresAt: Date; userAgent?: string; ipAddress?: string; rotatedFromId?: string }) { const [row] = await this.database.db.insert(customerSessions).values(input).returning({ id: customerSessions.id }); if (!row) throw new Error("Customer session creation failed."); return row.id; }
  async revokeSession(sessionId: string) { await this.database.db.update(customerSessions).set({ revokedAt: new Date() }).where(eq(customerSessions.id, sessionId)); }
  async createToken(input: { customerId: string; type: "email_verification" | "password_reset"; tokenHash: string; expiresAt: Date }) { await this.database.db.insert(customerTokens).values(input); }
  async consumePasswordReset(tokenHash: string, passwordHash: string) { return this.database.db.transaction(async (tx) => { const [token] = await tx.select().from(customerTokens).where(and(eq(customerTokens.tokenHash, tokenHash), eq(customerTokens.type, "password_reset"), gt(customerTokens.expiresAt, new Date()), isNull(customerTokens.usedAt))).limit(1).for("update"); if (!token) return false; await tx.update(customers).set({ passwordHash, updatedAt: new Date() }).where(eq(customers.id, token.customerId)); await tx.update(customerTokens).set({ usedAt: new Date() }).where(eq(customerTokens.id, token.id)); await tx.update(customerSessions).set({ revokedAt: new Date() }).where(and(eq(customerSessions.customerId, token.customerId), isNull(customerSessions.revokedAt))); return true; }); }
  async mergeGuestCart(input: { storeId: string; customerId: string; guestTokenHash?: string }) { const guestTokenHash = input.guestTokenHash; if (!guestTokenHash) return; await this.database.db.transaction(async (tx) => { const [guest] = await tx.select({ id: carts.id }).from(carts).where(and(eq(carts.storeId, input.storeId), eq(carts.guestTokenHash, guestTokenHash), eq(carts.status, "active"))).limit(1).for("update"); if (!guest) return; const [customerCart] = await tx.select({ id: carts.id }).from(carts).where(and(eq(carts.storeId, input.storeId), eq(carts.customerId, input.customerId), eq(carts.status, "active"))).limit(1).for("update"); if (!customerCart) { await tx.update(carts).set({ customerId: input.customerId, updatedAt: new Date() }).where(eq(carts.id, guest.id)); return; } const items = await tx.select().from(cartItems).where(eq(cartItems.cartId, guest.id)); for (const item of items) { await tx.insert(cartItems).values({ ...item, id: undefined, cartId: customerCart.id }).onConflictDoUpdate({ target: [cartItems.cartId, cartItems.variantId], set: { quantity: item.quantity, unitPriceMinor: item.unitPriceMinor, updatedAt: new Date() } }); } await tx.update(carts).set({ status: "abandoned", updatedAt: new Date() }).where(eq(carts.id, guest.id)); }); }
  listAddresses(storeId: string, customerId: string) { return this.database.db.select().from(customerAddresses).where(and(eq(customerAddresses.storeId, storeId), eq(customerAddresses.customerId, customerId))).orderBy(asc(customerAddresses.createdAt)).then((rows) => rows.map(address)); }
  async createAddress(storeId: string, customerId: string, input: CustomerAddressInputDto) { return this.database.db.transaction(async (tx) => { if (input.isDefaultShipping) await tx.update(customerAddresses).set({ isDefaultShipping: false }).where(eq(customerAddresses.customerId, customerId)); if (input.isDefaultBilling) await tx.update(customerAddresses).set({ isDefaultBilling: false }).where(eq(customerAddresses.customerId, customerId)); const [row] = await tx.insert(customerAddresses).values({ storeId, customerId, ...input, countryCode: input.countryCode.toUpperCase() }).returning(); if (!row) throw new Error("Address creation failed."); return address(row); }); }
  async updateAddress(storeId: string, customerId: string, addressId: string, input: CustomerAddressInputDto) { return this.database.db.transaction(async (tx) => { if (input.isDefaultShipping) await tx.update(customerAddresses).set({ isDefaultShipping: false }).where(eq(customerAddresses.customerId, customerId)); if (input.isDefaultBilling) await tx.update(customerAddresses).set({ isDefaultBilling: false }).where(eq(customerAddresses.customerId, customerId)); const [row] = await tx.update(customerAddresses).set({ ...input, countryCode: input.countryCode.toUpperCase(), updatedAt: new Date() }).where(and(eq(customerAddresses.id, addressId), eq(customerAddresses.storeId, storeId), eq(customerAddresses.customerId, customerId))).returning(); return row ? address(row) : null; }); }
  async deleteAddress(storeId: string, customerId: string, addressId: string) { const rows = await this.database.db.delete(customerAddresses).where(and(eq(customerAddresses.id, addressId), eq(customerAddresses.storeId, storeId), eq(customerAddresses.customerId, customerId))).returning({ id: customerAddresses.id }); return rows.length > 0; }
}
