import { ConflictException, Injectable, NotFoundException, UnauthorizedException } from "@nestjs/common";
import { createHash, randomBytes } from "node:crypto";
import { PasswordService } from "../../auth/services/password.service";
import { CartService } from "../../cart/services/cart.service";
import { StorefrontService } from "../../storefront/services";
import type { CustomerAddressInputDto, CustomerForgotPasswordDto, CustomerLoginDto, CustomerRegisterDto, CustomerResetPasswordDto, UpdateCustomerProfileDto } from "../dto";
import { CustomerRepository } from "../repositories";
@Injectable()
export class CustomerService {
  constructor(private readonly repository: CustomerRepository, private readonly password: PasswordService, private readonly storefront: StorefrontService, private readonly cart: CartService) {}
  private hash(value: string) { return createHash("sha256").update(value).digest("hex"); }
  private sessionToken() { return randomBytes(32).toString("base64url"); }
  async register(host: string | undefined, input: CustomerRegisterDto, context: { guestCartToken?: string; userAgent?: string; ipAddress?: string }) { const store = await this.storefront.resolve(host, input); const created = await this.repository.create({ storeId: store.storeId, email: input.email.toLowerCase(), passwordHash: await this.password.hash(input.password), firstName: input.firstName.trim(), lastName: input.lastName.trim(), phone: input.phone?.trim(), marketingConsent: input.marketingConsent ?? false }); if (created === "duplicate") throw new ConflictException({ code: "CUSTOMER_EMAIL_EXISTS", message: "An account already exists for this email." }); return this.issue(created, store.storeId, context); }
  async login(host: string | undefined, input: CustomerLoginDto, context: { guestCartToken?: string; userAgent?: string; ipAddress?: string }) { const store = await this.storefront.resolve(host, input); const customer = await this.repository.findByEmail(store.storeId, input.email.toLowerCase()); if (!customer || customer.status !== "active" || !(await this.password.verify(customer.passwordHash, input.password))) throw new UnauthorizedException({ code: "CUSTOMER_CREDENTIALS_INVALID", message: "Email or password is incorrect." }); return this.issue(customer, store.storeId, context); }
  private async issue(customer: { id: string; email: string; firstName: string; lastName: string; phone: string | null; emailVerified: boolean; marketingConsent: boolean }, storeId: string, context: { guestCartToken?: string; userAgent?: string; ipAddress?: string }, rotatedFromId?: string) { const token = this.sessionToken(); const sessionId = await this.repository.createSession({ customerId: customer.id, storeId, tokenHash: this.hash(token), expiresAt: new Date(Date.now() + 30 * 86400000), userAgent: context.userAgent, ipAddress: context.ipAddress, rotatedFromId }); await this.repository.mergeGuestCart({ storeId, customerId: customer.id, guestTokenHash: context.guestCartToken ? this.cart.hash(context.guestCartToken) : undefined }); return { token, sessionId, customer }; }
  async refresh(customer: { customerId: string; storeId: string; sessionId: string }, context: { userAgent?: string; ipAddress?: string }) { const profile = await this.repository.findById(customer.storeId, customer.customerId); if (!profile) throw new UnauthorizedException({ code: "CUSTOMER_SESSION_INVALID", message: "Customer session is invalid." }); await this.repository.revokeSession(customer.sessionId); return this.issue(profile, customer.storeId, context, customer.sessionId); }
  logout(sessionId: string) { return this.repository.revokeSession(sessionId); }
  async forgot(host: string | undefined, input: CustomerForgotPasswordDto) { const store = await this.storefront.resolve(host, input); const customer = await this.repository.findByEmail(store.storeId, input.email.toLowerCase()); if (customer) { const raw = randomBytes(32).toString("base64url"); await this.repository.createToken({ customerId: customer.id, type: "password_reset", tokenHash: this.hash(raw), expiresAt: new Date(Date.now() + 3600000) }); } return { message: "If the account exists, password reset instructions will be sent." }; }
  async reset(input: CustomerResetPasswordDto) { const ok = await this.repository.consumePasswordReset(this.hash(input.token), await this.password.hash(input.password)); if (!ok) throw new NotFoundException({ code: "PASSWORD_RESET_TOKEN_INVALID", message: "Reset token is invalid or expired." }); return { message: "Password reset successfully." }; }
  async profile(storeId: string, customerId: string) { const result = await this.repository.findById(storeId, customerId); if (!result) throw new NotFoundException({ code: "CUSTOMER_NOT_FOUND", message: "Customer not found." }); return result; }
  async update(storeId: string, customerId: string, input: UpdateCustomerProfileDto) { const result = await this.repository.updateProfile(storeId, customerId, input); if (!result) throw new NotFoundException({ code: "CUSTOMER_NOT_FOUND", message: "Customer not found." }); return result; }
  addresses(storeId: string, customerId: string) { return this.repository.listAddresses(storeId, customerId).then((items) => ({ items })); }
  createAddress(storeId: string, customerId: string, input: CustomerAddressInputDto) { return this.repository.createAddress(storeId, customerId, input); }
  async updateAddress(storeId: string, customerId: string, addressId: string, input: CustomerAddressInputDto) { const result = await this.repository.updateAddress(storeId, customerId, addressId, input); if (!result) throw new NotFoundException({ code: "CUSTOMER_ADDRESS_NOT_FOUND", message: "Address not found." }); return result; }
  async deleteAddress(storeId: string, customerId: string, addressId: string) { if (!(await this.repository.deleteAddress(storeId, customerId, addressId))) throw new NotFoundException({ code: "CUSTOMER_ADDRESS_NOT_FOUND", message: "Address not found." }); return { message: "Address deleted." }; }
}
