"use client";
import { useCheckoutSaveAddress, useCheckoutStart, useOrderPlace, usePublicPaymentMethods, usePublicPromotionsApply, usePublicPromotionsSelect, usePublicPromotionsShipping, useStorefrontResolve } from "@brandcanvas/contracts";
import { LoadingState } from "@brandcanvas/ui";
import Alert from "@mui/material/Alert";
import Button from "@mui/material/Button";
import Grid from "@mui/material/Grid";
import Paper from "@mui/material/Paper";
import Stack from "@mui/material/Stack";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { StorefrontShell } from "@/features/storefront/ui/storefront-shell";

export function CheckoutPage(){
 const {storeSlug}=useParams<{storeSlug:string}>();const router=useRouter();const store=useStorefrontResolve({storeSlug});const start=useCheckoutStart();const save=useCheckoutSaveAddress();const place=useOrderPlace();const [checkout,setCheckout]=useState<Awaited<ReturnType<typeof start.mutateAsync>>|null>(null);const key=useMemo(()=>typeof window==="undefined"?"":sessionStorage.getItem(`checkout-key:${storeSlug}`)??crypto.randomUUID(),[storeSlug]);
 useEffect(()=>{if(!key||start.isPending||start.data||start.isError)return;sessionStorage.setItem(`checkout-key:${storeSlug}`,key);start.mutateAsync({data:{storeSlug,idempotencyKey:key}}).then(setCheckout).catch(()=>undefined)},[key,storeSlug,start]);
 const [coupon,setCoupon]=useState("");const shipping=usePublicPromotionsShipping({storeSlug,countryCode:"PK"});const paymentMethods=usePublicPaymentMethods({storeSlug});const applyCoupon=usePublicPromotionsApply();const selectShipping=usePublicPromotionsSelect();
 const [form,setForm]=useState({guestEmail:"",firstName:"",lastName:"",phone:"",addressLine1:"",addressLine2:"",city:"",region:"",postalCode:"",countryCode:"PK"});
 if(store.isPending||start.isPending)return <LoadingState label="Reserving your cart…"/>;if(store.isError||!store.data)return <Alert severity="warning">Storefront unavailable.</Alert>;
 const current=save.data??checkout??start.data;
 return <StorefrontShell storefront={store.data}><Stack spacing={3}><Typography variant="h3">Checkout</Typography>{start.isError?<Alert severity="error">Unable to start checkout. Review your cart and stock availability.</Alert>:null}{current?<Grid container spacing={3}><Grid size={{xs:12,md:7}}><Paper variant="outlined" sx={{p:3}}><Stack spacing={2}><Typography variant="h5">Contact and delivery address</Typography>{Object.entries(form).map(([field,value])=><TextField key={field} label={field.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase())} value={value} onChange={(e)=>setForm({...form,[field]:e.target.value})} required={!['addressLine2','postalCode'].includes(field)}/>) }<Button variant="contained" disabled={save.isPending} onClick={()=>save.mutateAsync({checkoutId:current.id,data:{storeSlug,type:"shipping",...form}}).then(setCheckout)}>{save.isPending?"Saving…":"Save and review"}</Button>{save.isError?<Alert severity="error">Please check the address fields.</Alert>:null}</Stack></Paper></Grid><Grid size={{xs:12,md:5}}><Paper sx={{p:3}}><Stack spacing={2}><Typography variant="h5">Order summary</Typography>{current.items.map((item)=><Stack key={item.variantId} direction="row" justifyContent="space-between"><Typography>{item.name} × {item.quantity}</Typography><Typography>{current.currency} {(item.lineTotalMinor/100).toFixed(2)}</Typography></Stack>)}<TextField label="Coupon code" value={coupon} onChange={e=>setCoupon(e.target.value)}/><Button variant="outlined" disabled={!coupon||applyCoupon.isPending} onClick={()=>applyCoupon.mutateAsync({checkoutId:current.id,data:{storeSlug,code:coupon}}).then(setCheckout)}>Apply coupon</Button>{shipping.data?.items.map(method=><Button key={method.id} variant="outlined" onClick={()=>selectShipping.mutateAsync({checkoutId:current.id,data:{storeSlug,methodCode:method.code}}).then(setCheckout)}>{method.name} · {current.currency} {(method.rateMinor/100).toFixed(2)}</Button>)}<Typography variant="h6" fontWeight={900}>Total: {current.currency} {(current.totalMinor/100).toFixed(2)}</Typography>{paymentMethods.data?.items.some(method=>method.code==="cod")?<Alert severity="info">Payment method: Cash on Delivery</Alert>:<Alert severity="warning">No payment method is enabled.</Alert>}<Button variant="contained" size="large" disabled={!current.addresses.some(a=>a.type==="shipping")||place.isPending||!paymentMethods.data?.items.some(method=>method.code==="cod")} onClick={()=>place.mutateAsync({data:{storeSlug,checkoutId:current.id,idempotencyKey:`order:${current.id}`,paymentMethod:"cod"}}).then(order=>router.push(`/store/${storeSlug}/order-confirmation/${order.publicReference}?email=${encodeURIComponent(order.customerEmail)}`))}>{place.isPending?"Placing order…":"Place order"}</Button>{place.isError?<Alert severity="error">Unable to place the order. Refresh the checkout and try again.</Alert>:null}</Stack></Paper></Grid></Grid>:null}</Stack></StorefrontShell>;
}
