import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";
import { IsBoolean, IsEmail, IsOptional, IsString, IsUUID, Length, Matches, MaxLength, MinLength } from "class-validator";
class StoreSlugDto { @ApiProperty() @IsString() @MaxLength(150) @Matches(/^[a-z0-9]+(?:-[a-z0-9]+)*$/) storeSlug!: string; }
export class CustomerRegisterDto extends StoreSlugDto { @ApiProperty() @IsEmail() email!: string; @ApiProperty({ minLength: 10 }) @IsString() @MinLength(10) @MaxLength(128) password!: string; @ApiProperty() @IsString() @MaxLength(80) firstName!: string; @ApiProperty() @IsString() @MaxLength(80) lastName!: string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(32) phone?: string; @ApiPropertyOptional({ default: false }) @IsOptional() @IsBoolean() marketingConsent?: boolean; }
export class CustomerLoginDto extends StoreSlugDto { @ApiProperty() @IsEmail() email!: string; @ApiProperty() @IsString() password!: string; }
export class CustomerForgotPasswordDto extends StoreSlugDto { @ApiProperty() @IsEmail() email!: string; }
export class CustomerResetPasswordDto { @ApiProperty() @IsString() token!: string; @ApiProperty({ minLength: 10 }) @IsString() @MinLength(10) @MaxLength(128) password!: string; }
export class CustomerProfileDto { @ApiProperty({ format: "uuid" }) id!: string; @ApiProperty() email!: string; @ApiProperty() firstName!: string; @ApiProperty() lastName!: string; @ApiPropertyOptional({ nullable: true }) phone!: string | null; @ApiProperty() emailVerified!: boolean; @ApiProperty() marketingConsent!: boolean; }
export class UpdateCustomerProfileDto { @ApiProperty() @IsString() @MaxLength(80) firstName!: string; @ApiProperty() @IsString() @MaxLength(80) lastName!: string; @ApiPropertyOptional({ nullable: true }) @IsOptional() @IsString() @MaxLength(32) phone?: string | null; @ApiPropertyOptional() @IsOptional() @IsBoolean() marketingConsent?: boolean; }
export class CustomerAuthResponseDto { @ApiProperty({ type: CustomerProfileDto }) customer!: CustomerProfileDto; }
export class CustomerAddressInputDto { @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(80) label?: string; @ApiProperty() @IsString() @MaxLength(80) firstName!: string; @ApiProperty() @IsString() @MaxLength(80) lastName!: string; @ApiProperty() @IsString() @MaxLength(32) phone!: string; @ApiProperty() @IsString() @MaxLength(200) addressLine1!: string; @ApiPropertyOptional({ nullable: true }) @IsOptional() @IsString() @MaxLength(200) addressLine2?: string | null; @ApiProperty() @IsString() @MaxLength(100) city!: string; @ApiProperty() @IsString() @MaxLength(100) region!: string; @ApiPropertyOptional({ nullable: true }) @IsOptional() @IsString() @MaxLength(24) postalCode?: string | null; @ApiProperty() @IsString() @Length(2, 2) countryCode!: string; @ApiPropertyOptional() @IsOptional() @IsBoolean() isDefaultShipping?: boolean; @ApiPropertyOptional() @IsOptional() @IsBoolean() isDefaultBilling?: boolean; }
export class CustomerAddressDto extends CustomerAddressInputDto { @ApiProperty({ format: "uuid" }) id!: string; }
export class CustomerAddressListDto { @ApiProperty({ type: [CustomerAddressDto] }) items!: CustomerAddressDto[]; }
export class CustomerMessageDto { @ApiProperty() message!: string; }
