import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";import { Type } from "class-transformer";import { IsArray,IsBoolean,IsIn,IsInt,IsOptional,IsString,IsUUID,Max,MaxLength,Min } from "class-validator";
export class CreateDiscountDto{@ApiProperty()@IsString()@MaxLength(150)name!:string;@ApiProperty({enum:["percentage","fixed_amount","free_shipping"]})@IsIn(["percentage","fixed_amount","free_shipping"])type!:"percentage"|"fixed_amount"|"free_shipping";@ApiProperty({minimum:0})@Type(()=>Number)@IsInt()@Min(0)value!:number;@ApiPropertyOptional({enum:["draft","active","inactive"]})@IsOptional()@IsIn(["draft","active","inactive"])status?:"draft"|"active"|"inactive";@ApiPropertyOptional()@IsOptional()@Type(()=>Number)@IsInt()@Min(0)minimumSubtotalMinor?:number;@ApiPropertyOptional()@IsOptional()@Type(()=>Number)@IsInt()@Min(1)usageLimit?:number;@ApiPropertyOptional()@IsOptional()@IsString()@MaxLength(80)couponCode?:string;}
export class DiscountResponseDto{@ApiProperty({format:"uuid"})id!:string;@ApiProperty()name!:string;@ApiProperty()type!:string;@ApiProperty()value!:number;@ApiProperty()status!:string;@ApiProperty()minimumSubtotalMinor!:number;@ApiPropertyOptional({nullable:true})couponCode!:string|null;}
export class DiscountListResponseDto{@ApiProperty({type:[DiscountResponseDto]})items!:DiscountResponseDto[];}
export class ApplyCouponDto{@ApiProperty()@IsString()@MaxLength(150)storeSlug!:string;@ApiProperty()@IsString()@MaxLength(80)code!:string;}
export class SelectShippingDto{@ApiProperty()@IsString()@MaxLength(150)storeSlug!:string;@ApiProperty()@IsString()@MaxLength(80)methodCode!:string;}
export class CreateShippingZoneDto{@ApiProperty()@IsString()@MaxLength(120)name!:string;@ApiProperty({type:[String]})@IsArray()countryCodes!:string[];}
export class CreateShippingMethodDto{@ApiProperty({format:"uuid"})@IsUUID()zoneId!:string;@ApiProperty()@IsString()@MaxLength(80)code!:string;@ApiProperty()@IsString()@MaxLength(120)name!:string;@ApiProperty()@Type(()=>Number)@IsInt()@Min(0)rateMinor!:number;@ApiPropertyOptional()@IsOptional()@Type(()=>Number)@IsInt()@Min(0)freeAboveMinor?:number;@ApiPropertyOptional()@IsOptional()@Type(()=>Number)@IsInt()@Min(1)estimatedDaysMin?:number;@ApiPropertyOptional()@IsOptional()@Type(()=>Number)@IsInt()@Min(1)estimatedDaysMax?:number;@ApiPropertyOptional()@IsOptional()@IsBoolean()isActive?:boolean;}
export class ShippingMethodResponseDto{@ApiProperty({format:"uuid"})id!:string;@ApiProperty()code!:string;@ApiProperty()name!:string;@ApiProperty()rateMinor!:number;@ApiPropertyOptional({nullable:true})freeAboveMinor!:number|null;@ApiPropertyOptional({nullable:true})estimatedDaysMin!:number|null;@ApiPropertyOptional({nullable:true})estimatedDaysMax!:number|null;}
export class ShippingMethodListDto{@ApiProperty({type:[ShippingMethodResponseDto]})items!:ShippingMethodResponseDto[];}

export class PublicShippingQueryDto{@ApiProperty()@IsString()@MaxLength(150)storeSlug!:string;@ApiPropertyOptional()@IsOptional()@IsString()countryCode?:string;}
