import { defineConfig } from "orval";

export default defineConfig({
  brandcanvas: {
    input: {
      target: "./openapi/brandcanvas.openapi.json",
    },
    output: {
      mode: "tags-split",
      target: "./src/generated/endpoints.ts",
      schemas: {
        path: "./src/generated/models",
        type: "typescript",
        splitByTags: true,
      },
      client: "react-query",
      httpClient: "fetch",
      clean: true,
      formatter: "prettier",
      indexFiles: true,
      tagsSplitDeduplication: true,
      override: {
        header: () => ["Generated by Orval from BrandCanvas OpenAPI.", "Do not edit manually."],
        mutator: {
          path: "./src/client/api-fetcher.ts",
          name: "apiFetcher",
        },
        fetch: {
          includeHttpResponseReturnType: false,
        },
        query: {
          signal: true,
        },
      },
    },
  },
});
