import { Injectable } from "@nestjs/common";
import { cartItems,carts,checkoutAddresses,checkoutSessions,inventoryItems,inventoryMovements,inventoryReservations,products,productVariants } from "@brandcanvas/database";
import { and,asc,eq,inArray,sql } from "drizzle-orm";
import { DatabaseService } from "../../../infrastructure/database";
import type { CheckoutAddressDto,CheckoutItemDto,CheckoutResponseDto,SaveCheckoutAddressDto } from "../dto";
import { CheckoutRepository } from "./checkout.repository";
@Injectable()
export class DrizzleCheckoutRepository implements CheckoutRepository{
 constructor(private readonly database:DatabaseService){}
 async start(input:{storeId:string;storeSlug:string;guestTokenHash:string;idempotencyKey:string;expiresAt:Date}){
  return this.database.db.transaction(async(tx)=>{
   const [existing]=await tx.select({id:checkoutSessions.id}).from(checkoutSessions).where(and(eq(checkoutSessions.storeId,input.storeId),eq(checkoutSessions.idempotencyKey,input.idempotencyKey))).limit(1);if(existing){const existingCheckout=await this.read(tx,input.storeId,input.storeSlug,input.guestTokenHash,existing.id);if(!existingCheckout)throw new Error("Checkout idempotency conflict.");return existingCheckout;}
   const [cart]=await tx.select({id:carts.id,currency:carts.currency}).from(carts).where(and(eq(carts.storeId,input.storeId),eq(carts.guestTokenHash,input.guestTokenHash),eq(carts.status,"active"))).limit(1);if(!cart)return "cart_empty" as const;
   const items=await tx.select({productId:cartItems.productId,variantId:cartItems.variantId,quantity:cartItems.quantity,name:products.name,variantTitle:productVariants.title,price:sql<number>`coalesce(${productVariants.priceOverrideMinor},${products.priceMinor})`,inventoryItemId:inventoryItems.id,stock:inventoryItems.stockQuantity,reserved:inventoryItems.reservedQuantity}).from(cartItems).innerJoin(products,eq(products.id,cartItems.productId)).innerJoin(productVariants,eq(productVariants.id,cartItems.variantId)).innerJoin(inventoryItems,eq(inventoryItems.variantId,cartItems.variantId)).where(eq(cartItems.cartId,cart.id)).orderBy(asc(inventoryItems.id)).for("update");
   if(!items.length)return "cart_empty" as const;if(items.some(i=>i.stock-i.reserved<i.quantity))return "insufficient_stock" as const;
   const subtotal=items.reduce((n,i)=>n+i.price*i.quantity,0);const [checkout]=await tx.insert(checkoutSessions).values({storeId:input.storeId,cartId:cart.id,guestTokenHash:input.guestTokenHash,currency:cart.currency,subtotalMinor:subtotal,totalMinor:subtotal,idempotencyKey:input.idempotencyKey,expiresAt:input.expiresAt}).returning({id:checkoutSessions.id});if(!checkout)throw new Error("Unable to create checkout.");
   for(const item of items){const next=item.reserved+item.quantity;await tx.update(inventoryItems).set({reservedQuantity:next,updatedAt:new Date()}).where(and(eq(inventoryItems.id,item.inventoryItemId),eq(inventoryItems.reservedQuantity,item.reserved)));const key=`checkout:${checkout.id}:${item.inventoryItemId}`;await tx.insert(inventoryReservations).values({storeId:input.storeId,productId:item.productId,variantId:item.variantId,inventoryItemId:item.inventoryItemId,quantity:item.quantity,status:"active",referenceType:"checkout",referenceId:checkout.id,idempotencyKey:key,expiresAt:input.expiresAt});await tx.insert(inventoryMovements).values({storeId:input.storeId,productId:item.productId,variantId:item.variantId,inventoryItemId:item.inventoryItemId,movementType:"reservation",quantityDelta:0,stockBefore:item.stock,stockAfter:item.stock,reservedBefore:item.reserved,reservedAfter:next,reason:"Checkout reservation",referenceType:"checkout",referenceId:checkout.id,idempotencyKey:key});}
   const createdCheckout=await this.read(tx,input.storeId,input.storeSlug,input.guestTokenHash,checkout.id);if(!createdCheckout)throw new Error("Unable to read created checkout.");return createdCheckout;
  });
 }
 async get(input:{storeId:string;storeSlug:string;guestTokenHash:string;checkoutId:string}){return this.read(this.database.db,input.storeId,input.storeSlug,input.guestTokenHash,input.checkoutId);}
 async saveAddress(input:{storeId:string;storeSlug:string;guestTokenHash:string;checkoutId:string;address:SaveCheckoutAddressDto}){return this.database.db.transaction(async(tx)=>{const [owned]=await tx.select({id:checkoutSessions.id}).from(checkoutSessions).where(and(eq(checkoutSessions.id,input.checkoutId),eq(checkoutSessions.storeId,input.storeId),eq(checkoutSessions.guestTokenHash,input.guestTokenHash),inArray(checkoutSessions.status,["active","ready"]))).limit(1);if(!owned)return null;const a=input.address;await tx.insert(checkoutAddresses).values({checkoutSessionId:input.checkoutId,type:a.type,firstName:a.firstName.trim(),lastName:a.lastName.trim(),phone:a.phone.trim(),addressLine1:a.addressLine1.trim(),addressLine2:a.addressLine2?.trim()||null,city:a.city.trim(),region:a.region.trim(),postalCode:a.postalCode?.trim()||null,countryCode:a.countryCode.toUpperCase()}).onConflictDoUpdate({target:[checkoutAddresses.checkoutSessionId,checkoutAddresses.type],set:{firstName:a.firstName.trim(),lastName:a.lastName.trim(),phone:a.phone.trim(),addressLine1:a.addressLine1.trim(),addressLine2:a.addressLine2?.trim()||null,city:a.city.trim(),region:a.region.trim(),postalCode:a.postalCode?.trim()||null,countryCode:a.countryCode.toUpperCase(),updatedAt:new Date()}});await tx.update(checkoutSessions).set({guestEmail:a.guestEmail?.toLowerCase(),status:a.type==="shipping"?"ready":undefined,updatedAt:new Date()}).where(eq(checkoutSessions.id,input.checkoutId));return this.read(tx,input.storeId,input.storeSlug,input.guestTokenHash,input.checkoutId);});}
 async cancel(input:{storeId:string;storeSlug:string;guestTokenHash:string;checkoutId:string}){return this.database.db.transaction(async(tx)=>{const [checkout]=await tx.select({id:checkoutSessions.id,status:checkoutSessions.status}).from(checkoutSessions).where(and(eq(checkoutSessions.id,input.checkoutId),eq(checkoutSessions.storeId,input.storeId),eq(checkoutSessions.guestTokenHash,input.guestTokenHash))).limit(1).for("update");if(!checkout)return null;if(checkout.status==="cancelled")return this.read(tx,input.storeId,input.storeSlug,input.guestTokenHash,input.checkoutId);const reservations=await tx.select().from(inventoryReservations).where(and(eq(inventoryReservations.storeId,input.storeId),eq(inventoryReservations.referenceType,"checkout"),eq(inventoryReservations.referenceId,input.checkoutId),eq(inventoryReservations.status,"active"))).for("update");for(const reservation of reservations){const [item]=await tx.select().from(inventoryItems).where(eq(inventoryItems.id,reservation.inventoryItemId)).limit(1).for("update");if(!item)continue;const next=Math.max(0,item.reservedQuantity-reservation.quantity);await tx.update(inventoryItems).set({reservedQuantity:next,updatedAt:new Date()}).where(eq(inventoryItems.id,item.id));await tx.update(inventoryReservations).set({status:"cancelled",releasedAt:new Date(),updatedAt:new Date()}).where(eq(inventoryReservations.id,reservation.id));await tx.insert(inventoryMovements).values({storeId:input.storeId,productId:item.productId,variantId:item.variantId,inventoryItemId:item.id,movementType:"reservation_release",quantityDelta:0,stockBefore:item.stockQuantity,stockAfter:item.stockQuantity,reservedBefore:item.reservedQuantity,reservedAfter:next,reason:"Checkout cancelled",referenceType:"checkout",referenceId:input.checkoutId,idempotencyKey:`checkout-cancel:${reservation.id}`});}await tx.update(checkoutSessions).set({status:"cancelled",updatedAt:new Date()}).where(eq(checkoutSessions.id,input.checkoutId));return this.read(tx,input.storeId,input.storeSlug,input.guestTokenHash,input.checkoutId);});}
 private async read(db:any,storeId:string,storeSlug:string,guestTokenHash:string,checkoutId:string):Promise<CheckoutResponseDto|null>{const [c]=await db.select().from(checkoutSessions).where(and(eq(checkoutSessions.id,checkoutId),eq(checkoutSessions.storeId,storeId),eq(checkoutSessions.guestTokenHash,guestTokenHash))).limit(1);if(!c)return null;const [items,addresses]=await Promise.all([db.select({productId:cartItems.productId,variantId:cartItems.variantId,name:products.name,variantTitle:productVariants.title,quantity:cartItems.quantity,unitPriceMinor:sql<number>`coalesce(${productVariants.priceOverrideMinor},${products.priceMinor})`}).from(cartItems).innerJoin(products,eq(products.id,cartItems.productId)).innerJoin(productVariants,eq(productVariants.id,cartItems.variantId)).where(eq(cartItems.cartId,c.cartId)),db.select().from(checkoutAddresses).where(eq(checkoutAddresses.checkoutSessionId,c.id))]);const mappedItems:CheckoutItemDto[]=items.map((i:any)=>({...i,lineTotalMinor:i.unitPriceMinor*i.quantity}));const mappedAddresses:CheckoutAddressDto[]=addresses.map((a:any)=>({id:a.id,storeSlug,type:a.type,firstName:a.firstName,lastName:a.lastName,phone:a.phone,addressLine1:a.addressLine1,addressLine2:a.addressLine2,city:a.city,region:a.region,postalCode:a.postalCode,countryCode:a.countryCode}));return{id:c.id,cartId:c.cartId,storeSlug,status:c.status,currency:c.currency,items:mappedItems,addresses:mappedAddresses,subtotalMinor:c.subtotalMinor,discountMinor:c.discountMinor,shippingMinor:c.shippingMinor,taxMinor:c.taxMinor,totalMinor:c.totalMinor,expiresAt:c.expiresAt.toISOString()};}
}
