import { ApiProperty,ApiPropertyOptional } from "@nestjs/swagger";import { Type } from "class-transformer";import { IsBoolean,IsIn,IsInt,IsOptional,IsString,IsUUID,MaxLength,Min } from "class-validator";
export class CreatePlanDto{@ApiProperty()@IsString()@MaxLength(80)code!:string;@ApiProperty()@IsString()@MaxLength(120)name!:string;@ApiProperty()@Type(()=>Number)@IsInt()@Min(0)priceMinor!:number;@ApiProperty({enum:["monthly","yearly"]})@IsIn(["monthly","yearly"])billingInterval!:"monthly"|"yearly";@ApiProperty()@Type(()=>Number)@IsInt()@Min(0)productLimit!:number;@ApiProperty()@Type(()=>Number)@IsInt()@Min(0)staffLimit!:number;@ApiProperty()@Type(()=>Number)@IsInt()@Min(0)monthlyOrderLimit!:number;@ApiProperty()@Type(()=>Number)@IsInt()@Min(0)storageMbLimit!:number;@ApiPropertyOptional()@IsOptional()@IsBoolean()customDomainsEnabled?:boolean;@ApiPropertyOptional()@IsOptional()@IsBoolean()messagingEnabled?:boolean;}
export class PlanResponseDto extends CreatePlanDto{@ApiProperty({format:"uuid"})id!:string;@ApiProperty()currency!:string;@ApiProperty()isActive!:boolean;}
export class PlanListDto{@ApiProperty({type:[PlanResponseDto]})items!:PlanResponseDto[];}
export class AssignPlanDto{@ApiProperty({format:"uuid"})@IsUUID()storeId!:string;@ApiProperty({format:"uuid"})@IsUUID()planId!:string;@ApiPropertyOptional({format:"date-time"})@IsOptional()@IsString()endsAt?:string;}
export class SubscriptionResponseDto{@ApiProperty({format:"uuid"})id!:string;@ApiProperty({format:"uuid"})storeId!:string;@ApiProperty({type:PlanResponseDto})plan!:PlanResponseDto;@ApiProperty()status!:string;@ApiProperty({format:"date-time"})startsAt!:string;@ApiPropertyOptional({nullable:true,format:"date-time"})endsAt!:string|null;}
export class UsageResponseDto{@ApiProperty()productCount!:number;@ApiProperty()productLimit!:number;@ApiProperty()staffCount!:number;@ApiProperty()staffLimit!:number;@ApiProperty()orderCount!:number;@ApiProperty()orderLimit!:number;@ApiProperty()storageBytes!:number;@ApiProperty()storageLimitBytes!:number;}
export class SellerAnalyticsDto{@ApiProperty()revenueMinor!:number;@ApiProperty()orderCount!:number;@ApiProperty()averageOrderValueMinor!:number;@ApiProperty()lowStockCount!:number;@ApiProperty()productCount!:number;}
export class PlatformAnalyticsDto{@ApiProperty()totalStores!:number;@ApiProperty()activeStores!:number;@ApiProperty()suspendedStores!:number;@ApiProperty()totalOrders!:number;@ApiProperty()gmvMinor!:number;@ApiProperty()activeSubscriptions!:number;}
