import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";
import { Type } from "class-transformer";
import { IsIn, IsInt, IsOptional, IsString, IsUUID, Max, MaxLength, Min } from "class-validator";
export const ORDER_STATUSES=["pending_confirmation","confirmed","processing","packed","shipped","delivered","cancelled","returned","refunded"] as const;
export class PlaceOrderDto{ @ApiProperty()@IsString()@MaxLength(150)storeSlug!:string;@ApiProperty({format:"uuid"})@IsUUID()checkoutId!:string;@ApiProperty()@IsString()@MaxLength(120)idempotencyKey!:string;@ApiProperty({enum:["cod"]})@IsIn(["cod"])paymentMethod!:"cod";@ApiPropertyOptional()@IsOptional()@IsString()@MaxLength(500)notes?:string; }
export class TrackOrderQueryDto{ @ApiProperty()@IsString()@MaxLength(64)reference!:string;@ApiProperty()@IsString()@MaxLength(254)email!:string; }
export class SellerOrderQueryDto{ @ApiPropertyOptional({default:1})@Type(()=>Number)@IsInt()@Min(1)page=1;@ApiPropertyOptional({default:20})@Type(()=>Number)@IsInt()@Min(1)@Max(100)pageSize=20;@ApiPropertyOptional({enum:ORDER_STATUSES})@IsOptional()@IsIn(ORDER_STATUSES)status?:string;@ApiPropertyOptional()@IsOptional()@IsString()@MaxLength(100)search?:string; }
export class UpdateOrderStatusDto{ @ApiProperty({enum:ORDER_STATUSES})@IsIn(ORDER_STATUSES)status!:(typeof ORDER_STATUSES)[number];@ApiPropertyOptional()@IsOptional()@IsString()@MaxLength(500)note?:string; }
export class UpdateTrackingDto{ @ApiPropertyOptional()@IsOptional()@IsString()@MaxLength(100)carrier?:string;@ApiPropertyOptional()@IsOptional()@IsString()@MaxLength(150)trackingNumber?:string;@ApiPropertyOptional()@IsOptional()@IsString()@MaxLength(500)trackingUrl?:string; }
export class OrderItemResponseDto{ @ApiProperty()name!:string;@ApiProperty()variantTitle!:string;@ApiProperty()sku!:string;@ApiProperty()quantity!:number;@ApiProperty()unitPriceMinor!:number;@ApiProperty()lineTotalMinor!:number; }
export class OrderTimelineDto{ @ApiProperty()status!:string;@ApiPropertyOptional({nullable:true})note!:string|null;@ApiProperty({format:"date-time"})createdAt!:string; }
export class OrderResponseDto{ @ApiProperty({format:"uuid"})id!:string;@ApiProperty()orderNumber!:string;@ApiProperty()publicReference!:string;@ApiProperty()status!:string;@ApiProperty()paymentStatus!:string;@ApiProperty()fulfillmentStatus!:string;@ApiProperty()currency!:string;@ApiProperty()customerEmail!:string;@ApiPropertyOptional({nullable:true})customerPhone!:string|null;@ApiProperty({type:[OrderItemResponseDto]})items!:OrderItemResponseDto[];@ApiProperty({type:[OrderTimelineDto]})timeline!:OrderTimelineDto[];@ApiProperty()subtotalMinor!:number;@ApiProperty()discountMinor!:number;@ApiProperty()shippingMinor!:number;@ApiProperty()taxMinor!:number;@ApiProperty()totalMinor!:number;@ApiPropertyOptional({nullable:true})trackingNumber!:string|null;@ApiPropertyOptional({nullable:true})trackingUrl!:string|null;@ApiProperty({format:"date-time"})createdAt!:string; }
export class OrderListResponseDto{ @ApiProperty({type:[OrderResponseDto]})items!:OrderResponseDto[];@ApiProperty()page!:number;@ApiProperty()pageSize!:number;@ApiProperty()total!:number;@ApiProperty()totalPages!:number; }
